import ExcelJS from "exceljs";
import Papa from "papaparse";
import type { ExportColumn, ExportRow } from "./columns";

/** Professionally formatted XLSX: branded header, frozen row, filters, widths, clickable links. */
export async function buildXlsx(columns: ExportColumn[], rows: ExportRow[], meta: { title: string; generatedBy: string }): Promise<Buffer> {
  const wb = new ExcelJS.Workbook();
  wb.creator = "Ain AlTair Lead Intelligence";
  wb.created = new Date();
  const ws = wb.addWorksheet("Leads", { views: [{ state: "frozen", ySplit: 1 }] });
  ws.columns = columns.map((c) => ({ header: c.label, key: c.key, width: c.width ?? 16 }));
  const header = ws.getRow(1);
  header.height = 24;
  header.eachCell((cell) => {
    cell.font = { bold: true, color: { argb: "FFFFFFFF" }, name: "Arial", size: 10 };
    cell.fill = { type: "pattern", pattern: "solid", fgColor: { argb: "FF14213D" } };
    cell.alignment = { vertical: "middle" };
    cell.border = { bottom: { style: "thick", color: { argb: "FFE8461F" } } };
  });
  for (const r of rows) {
    const row = ws.addRow(Object.fromEntries(columns.map((c) => [c.key, c.value(r)])));
    columns.forEach((c, i) => {
      const cell = row.getCell(i + 1);
      cell.font = { name: "Arial", size: 10 };
      if (c.link && typeof cell.value === "string" && /^https?:\/\//.test(cell.value)) {
        cell.value = { text: cell.value, hyperlink: cell.value };
        cell.font = { name: "Arial", size: 10, color: { argb: "FF2A3D63" }, underline: true };
      }
      if (c.key === "tier" && cell.value === "HOT") cell.font = { name: "Arial", size: 10, bold: true, color: { argb: "FFB5310F" } };
    });
  }
  ws.autoFilter = { from: { row: 1, column: 1 }, to: { row: 1, column: columns.length } };
  const info = wb.addWorksheet("About");
  info.addRows([["Ain AlTair Lead Intelligence export"], ["Title", meta.title], ["Generated", new Date().toISOString()], ["Generated by", meta.generatedBy], ["Rows", rows.length], [], ["Sales Intent and AI fields are estimates/inferences, not verified facts."]]);
  info.getColumn(1).width = 22;
  info.getColumn(2).width = 60;
  return Buffer.from(await wb.xlsx.writeBuffer());
}

export function buildCsv(columns: ExportColumn[], rows: ExportRow[]): string {
  return "﻿" + Papa.unparse({ fields: columns.map((c) => c.label), data: rows.map((r) => columns.map((c) => c.value(r) ?? "")) });
}

export function buildJson(columns: ExportColumn[], rows: ExportRow[]): string {
  return JSON.stringify(rows.map((r) => Object.fromEntries(columns.map((c) => [c.key, c.value(r)]))), null, 2);
}

export function exportFilename(ext: string, d = new Date()) {
  return `AIN_ALTAIR_LEADS_${d.toISOString().slice(0, 10)}.${ext}`;
}
