/** Regenerates supabase/migrations/20261008000006_reference_data.sql from TS sources. */
import { writeFileSync } from "node:fs";
import { permissionsSql } from "./gen-permissions-sql";
import { DEFAULT_CATEGORIES } from "../src/lib/categories/taxonomy";
import { PROVIDER_CATALOG } from "../src/lib/providers/catalog";

const q = (s: string) => `'${s.replace(/'/g, "''")}'`;
const arr = (a: string[] = []) => (a.length ? `array[${a.map(q).join(",")}]::text[]` : `'{}'::text[]`);

const cats = DEFAULT_CATEGORIES.map(
  (c) => `  (null, ${q(c.key)}, ${q(c.name)}, ${arr(c.synonyms)}, ${arr(c.exclusions)}, ${arr(c.googleTypes)}, ${q(JSON.stringify(c.osm ?? []))}::jsonb, ${c.valueMultiplier ?? 1})`,
).join(",\n");

const providerRows = PROVIDER_CATALOG.map(
  (p) => `    (org_id, ${q(p.key)}, ${q(p.name)}, ${q(p.kind)}, ${p.defaultPriority}, ${p.defaultRateLimitPerMinute ?? "null"})`,
).join(",\n");

const sql = `-- ============================================================================
-- 0006 REFERENCE DATA — GENERATED by scripts/gen-reference-sql.ts. Do not edit
-- by hand; edit src/lib/auth/permissions.ts, src/lib/categories/taxonomy.ts or
-- src/lib/providers/catalog.ts and regenerate.
-- ============================================================================

${permissionsSql()}

-- Global default categories
insert into public.categories (organisation_id, key, name, synonyms, exclusions, google_types, osm_tags, value_multiplier) values
${cats}
on conflict do nothing;

-- Default organisation (Ain AlTair). Additional organisations can be added later.
insert into public.organisations (name, slug, default_currency, default_country_code, timezone)
values ('Ain AlTair', 'ain-altair', 'AED', 'AE', 'Asia/Dubai')
on conflict (slug) do nothing;

-- Register providers + default settings for every organisation (idempotent).
create or replace function public.bootstrap_organisation(org_id uuid)
returns void language plpgsql security definer set search_path = public as $$
begin
  insert into public.providers (organisation_id, key, name, kind, priority, rate_limit_per_minute) values
${providerRows}
  on conflict (organisation_id, key) do update set name = excluded.name, kind = excluded.kind;
  insert into public.org_settings (organisation_id) values (org_id) on conflict do nothing;
end $$;
revoke all on function public.bootstrap_organisation(uuid) from public, anon, authenticated;

select public.bootstrap_organisation(id) from public.organisations;

create or replace function public.on_organisation_created()
returns trigger language plpgsql security definer set search_path = public as $$
begin
  perform public.bootstrap_organisation(new.id);
  return new;
end $$;
create trigger organisations_bootstrap after insert on public.organisations
  for each row execute function public.on_organisation_created();
`;

writeFileSync("supabase/migrations/20261008000006_reference_data.sql", sql);
console.log("wrote reference data migration");
