-- ============================================================================
-- 0006 REFERENCE DATA — GENERATED by scripts/gen-reference-sql.ts. Do not edit
-- by hand; edit src/lib/auth/permissions.ts, src/lib/categories/taxonomy.ts or
-- src/lib/providers/catalog.ts and regenerate.
-- ============================================================================

-- BEGIN GENERATED PERMISSIONS (scripts/gen-permissions-sql.ts)
insert into public.roles (key, name, description, rank) values
  ('SUPER_ADMIN', 'Super Admin', 'Full system control, approvals and permanent deletion.', 100),
  ('ADMIN', 'Admin', 'Manages users, providers, scoring and configuration.', 80),
  ('MANAGER', 'Manager', 'Leads the sales team; sees team leads, assigns and approves research.', 60),
  ('SALES', 'Sales', 'Works their own leads: outreach, notes and follow-ups.', 40),
  ('RESEARCHER', 'Researcher', 'Runs lead searches, reviews research and imports data.', 40),
  ('VIEWER', 'Viewer', 'Read-only access to team leads and analytics.', 10)
on conflict (key) do update set name = excluded.name, description = excluded.description, rank = excluded.rank;
insert into public.permissions (key, description, category) values
  ('leads.view_own', 'View leads assigned to me', 'Leads'),
  ('leads.view_team', 'View my team''s leads and unassigned leads', 'Leads'),
  ('leads.view_all', 'View every lead in the organisation', 'Leads'),
  ('leads.create', 'Create leads manually', 'Leads'),
  ('leads.edit', 'Edit lead details and pipeline stage', 'Leads'),
  ('leads.assign', 'Assign leads to users and teams', 'Leads'),
  ('leads.archive', 'Archive (soft delete) leads', 'Leads'),
  ('leads.delete_permanent', 'Permanently delete leads', 'Leads'),
  ('leads.override', 'Override score, opportunity, website status, category and price', 'Leads'),
  ('leads.merge', 'Merge duplicate records', 'Leads'),
  ('leads.bulk', 'Run bulk actions', 'Leads'),
  ('search.run', 'Start lead searches', 'Research'),
  ('search.view', 'View searches, jobs and research results', 'Research'),
  ('search.manage_templates', 'Edit and delete any saved search', 'Research'),
  ('search.schedule', 'Schedule recurring searches', 'Research'),
  ('research.review', 'Review, qualify and reject research results', 'Research'),
  ('research.approve', 'Approve research results into the CRM', 'Research'),
  ('imports.run', 'Import CSV / XLSX / Google Sheets', 'Data'),
  ('exports.run', 'Export leads', 'Data'),
  ('outreach.log', 'Log outreach and manage follow-ups', 'Sales'),
  ('notes.create', 'Write notes', 'Sales'),
  ('analytics.view', 'View analytics and market intelligence', 'Insights'),
  ('assistant.use', 'Use the AI sales assistant', 'Insights'),
  ('admin.users', 'Approve, suspend and manage users and teams', 'Admin'),
  ('admin.approvals', 'Approve or reject sensitive operations', 'Admin'),
  ('admin.providers', 'Manage data providers and integrations', 'Admin'),
  ('admin.categories', 'Manage categories and synonyms', 'Admin'),
  ('admin.locations', 'Manage saved locations and territories', 'Admin'),
  ('admin.scoring', 'Manage scoring, pricing and quality gates', 'Admin'),
  ('admin.audit', 'View audit logs', 'Admin'),
  ('admin.settings', 'Manage system settings', 'Admin'),
  ('admin.data_purge', 'Purge data permanently', 'Admin')
on conflict (key) do update set description = excluded.description, category = excluded.category;
delete from public.role_permissions;
insert into public.role_permissions (role_key, permission_key) values
  ('SUPER_ADMIN', 'leads.view_own'),
  ('SUPER_ADMIN', 'leads.view_team'),
  ('SUPER_ADMIN', 'leads.view_all'),
  ('SUPER_ADMIN', 'leads.create'),
  ('SUPER_ADMIN', 'leads.edit'),
  ('SUPER_ADMIN', 'leads.assign'),
  ('SUPER_ADMIN', 'leads.archive'),
  ('SUPER_ADMIN', 'leads.delete_permanent'),
  ('SUPER_ADMIN', 'leads.override'),
  ('SUPER_ADMIN', 'leads.merge'),
  ('SUPER_ADMIN', 'leads.bulk'),
  ('SUPER_ADMIN', 'search.run'),
  ('SUPER_ADMIN', 'search.view'),
  ('SUPER_ADMIN', 'search.manage_templates'),
  ('SUPER_ADMIN', 'search.schedule'),
  ('SUPER_ADMIN', 'research.review'),
  ('SUPER_ADMIN', 'research.approve'),
  ('SUPER_ADMIN', 'imports.run'),
  ('SUPER_ADMIN', 'exports.run'),
  ('SUPER_ADMIN', 'outreach.log'),
  ('SUPER_ADMIN', 'notes.create'),
  ('SUPER_ADMIN', 'analytics.view'),
  ('SUPER_ADMIN', 'assistant.use'),
  ('SUPER_ADMIN', 'admin.users'),
  ('SUPER_ADMIN', 'admin.approvals'),
  ('SUPER_ADMIN', 'admin.providers'),
  ('SUPER_ADMIN', 'admin.categories'),
  ('SUPER_ADMIN', 'admin.locations'),
  ('SUPER_ADMIN', 'admin.scoring'),
  ('SUPER_ADMIN', 'admin.audit'),
  ('SUPER_ADMIN', 'admin.settings'),
  ('SUPER_ADMIN', 'admin.data_purge'),
  ('ADMIN', 'leads.view_own'),
  ('ADMIN', 'leads.view_team'),
  ('ADMIN', 'leads.view_all'),
  ('ADMIN', 'leads.create'),
  ('ADMIN', 'leads.edit'),
  ('ADMIN', 'leads.assign'),
  ('ADMIN', 'leads.archive'),
  ('ADMIN', 'leads.override'),
  ('ADMIN', 'leads.merge'),
  ('ADMIN', 'leads.bulk'),
  ('ADMIN', 'search.run'),
  ('ADMIN', 'search.view'),
  ('ADMIN', 'search.manage_templates'),
  ('ADMIN', 'search.schedule'),
  ('ADMIN', 'research.review'),
  ('ADMIN', 'research.approve'),
  ('ADMIN', 'imports.run'),
  ('ADMIN', 'exports.run'),
  ('ADMIN', 'outreach.log'),
  ('ADMIN', 'notes.create'),
  ('ADMIN', 'analytics.view'),
  ('ADMIN', 'assistant.use'),
  ('ADMIN', 'admin.users'),
  ('ADMIN', 'admin.providers'),
  ('ADMIN', 'admin.categories'),
  ('ADMIN', 'admin.locations'),
  ('ADMIN', 'admin.scoring'),
  ('ADMIN', 'admin.audit'),
  ('ADMIN', 'admin.settings'),
  ('MANAGER', 'leads.view_own'),
  ('MANAGER', 'leads.view_team'),
  ('MANAGER', 'leads.create'),
  ('MANAGER', 'leads.edit'),
  ('MANAGER', 'leads.assign'),
  ('MANAGER', 'leads.archive'),
  ('MANAGER', 'leads.override'),
  ('MANAGER', 'leads.merge'),
  ('MANAGER', 'leads.bulk'),
  ('MANAGER', 'search.run'),
  ('MANAGER', 'search.view'),
  ('MANAGER', 'search.manage_templates'),
  ('MANAGER', 'search.schedule'),
  ('MANAGER', 'research.review'),
  ('MANAGER', 'research.approve'),
  ('MANAGER', 'imports.run'),
  ('MANAGER', 'outreach.log'),
  ('MANAGER', 'notes.create'),
  ('MANAGER', 'exports.run'),
  ('MANAGER', 'analytics.view'),
  ('MANAGER', 'assistant.use'),
  ('SALES', 'leads.view_own'),
  ('SALES', 'leads.edit'),
  ('SALES', 'outreach.log'),
  ('SALES', 'notes.create'),
  ('SALES', 'exports.run'),
  ('SALES', 'analytics.view'),
  ('SALES', 'assistant.use'),
  ('RESEARCHER', 'leads.view_own'),
  ('RESEARCHER', 'leads.view_team'),
  ('RESEARCHER', 'leads.create'),
  ('RESEARCHER', 'leads.edit'),
  ('RESEARCHER', 'search.run'),
  ('RESEARCHER', 'search.view'),
  ('RESEARCHER', 'search.manage_templates'),
  ('RESEARCHER', 'research.review'),
  ('RESEARCHER', 'imports.run'),
  ('RESEARCHER', 'exports.run'),
  ('RESEARCHER', 'notes.create'),
  ('RESEARCHER', 'analytics.view'),
  ('RESEARCHER', 'assistant.use'),
  ('VIEWER', 'leads.view_team'),
  ('VIEWER', 'search.view'),
  ('VIEWER', 'analytics.view');
-- END GENERATED PERMISSIONS

-- Global default categories
insert into public.categories (organisation_id, key, name, synonyms, exclusions, google_types, osm_tags, value_multiplier) values
  (null, 'cleaning_services', 'Cleaning Services', array['cleaning','cleaners','cleaning company','deep cleaning','sofa cleaning','carpet cleaning','home cleaning','house cleaning','office cleaning','commercial cleaning','janitorial','residential cleaning','maid service','housekeeping']::text[], '{}'::text[], '{}'::text[], '[{"key":"craft","value":"cleaning"},{"key":"office","value":"cleaning"},{"key":"shop","value":"cleaning"}]'::jsonb, 1.1),
  (null, 'flower_shops', 'Flower Shops', array['florist','florists','flower shop','flowers','flower delivery','bouquets','floral design']::text[], '{}'::text[], array['florist']::text[], '[{"key":"shop","value":"florist"}]'::jsonb, 1),
  (null, 'salons', 'Salons', array['salon','beauty salon','ladies salon','beauty center','beauty centre','nail salon','nail spa','spa','hair salon','beauty parlour','lash studio','brow bar']::text[], '{}'::text[], array['beauty_salon','hair_salon','nail_salon','spa']::text[], '[{"key":"shop","value":"beauty"},{"key":"shop","value":"hairdresser"},{"key":"leisure","value":"spa"}]'::jsonb, 1.15),
  (null, 'barbers', 'Barbers', array['barber','barbershop','barber shop','gents salon','men''s salon','mens grooming']::text[], '{}'::text[], array['barber_shop']::text[], '[{"key":"shop","value":"hairdresser"}]'::jsonb, 0.9),
  (null, 'restaurants', 'Restaurants', array['restaurant','restaurants','eatery','diner','grill','kitchen','bistro','takeaway','food delivery']::text[], '{}'::text[], array['restaurant']::text[], '[{"key":"amenity","value":"restaurant"},{"key":"amenity","value":"fast_food"}]'::jsonb, 1.2),
  (null, 'cafeterias', 'Cafeterias & Cafés', array['cafe','café','cafes','coffee shop','coffee','cafeteria','karak','tea shop']::text[], '{}'::text[], array['cafe','coffee_shop','cafeteria']::text[], '[{"key":"amenity","value":"cafe"}]'::jsonb, 0.95),
  (null, 'car_detailing', 'Car Detailing', array['car detailing','auto detailing','ceramic coating','ppf','paint protection film','car polishing','window tinting']::text[], '{}'::text[], array['car_wash']::text[], '[{"key":"amenity","value":"car_wash"},{"key":"shop","value":"car"}]'::jsonb, 1.2),
  (null, 'mobile_car_wash', 'Mobile Car Wash', array['mobile car wash','car wash','doorstep car wash','waterless car wash','car cleaning']::text[], '{}'::text[], array['car_wash']::text[], '[{"key":"amenity","value":"car_wash"}]'::jsonb, 1),
  (null, 'pest_control', 'Pest Control', array['pest control','pest','exterminator','termite control','fumigation','bed bug treatment','disinfection']::text[], '{}'::text[], '{}'::text[], '[{"key":"craft","value":"pest_control"},{"key":"shop","value":"pest_control"}]'::jsonb, 1.15),
  (null, 'ac_maintenance', 'AC Maintenance', array['ac maintenance','ac repair','air conditioning','hvac','ac cleaning','duct cleaning','ac service']::text[], '{}'::text[], '{}'::text[], '[{"key":"craft","value":"hvac"}]'::jsonb, 1.2),
  (null, 'home_maintenance', 'Home Maintenance', array['home maintenance','handyman','maintenance company','plumber','plumbing','electrician','painting services','renovation','technical services','fit out']::text[], '{}'::text[], array['plumber','electrician','painter','general_contractor']::text[], '[{"key":"craft","value":"handyman"},{"key":"craft","value":"plumber"},{"key":"craft","value":"electrician"},{"key":"craft","value":"painter"}]'::jsonb, 1.15),
  (null, 'laundry', 'Laundry', array['laundry','dry cleaning','dry cleaners','laundromat','ironing','laundry service']::text[], '{}'::text[], array['laundry']::text[], '[{"key":"shop","value":"laundry"},{"key":"shop","value":"dry_cleaning"}]'::jsonb, 0.9),
  (null, 'pet_grooming', 'Pet Grooming', array['pet grooming','dog grooming','cat grooming','pet salon','pet spa','pet care']::text[], '{}'::text[], array['pet_care']::text[], '[{"key":"shop","value":"pet_grooming"}]'::jsonb, 1.05),
  (null, 'gyms', 'Gyms & Fitness', array['gym','gyms','fitness','fitness center','fitness centre','crossfit','personal training','yoga studio','pilates','martial arts']::text[], '{}'::text[], array['gym','fitness_center','yoga_studio']::text[], '[{"key":"leisure","value":"fitness_centre"},{"key":"sport","value":"fitness"}]'::jsonb, 1.15),
  (null, 'real_estate', 'Real Estate Agencies', array['real estate','real estate agency','property agency','estate agent','brokerage','property management','realtor']::text[], '{}'::text[], array['real_estate_agency']::text[], '[{"key":"office","value":"estate_agent"}]'::jsonb, 1.4),
  (null, 'dental_clinics', 'Dental Clinics', array['dental clinic','dentist','dentists','orthodontist','dental care','dental centre','dental center']::text[], '{}'::text[], array['dentist','dental_clinic']::text[], '[{"key":"amenity","value":"dentist"},{"key":"healthcare","value":"dentist"}]'::jsonb, 1.4),
  (null, 'accountants', 'Accountants', array['accountant','accountants','accounting firm','bookkeeping','audit firm','vat consultant','tax consultant','corporate tax']::text[], '{}'::text[], array['accounting']::text[], '[{"key":"office","value":"accountant"},{"key":"office","value":"tax_advisor"}]'::jsonb, 1.3),
  (null, 'law_firms', 'Law Firms', array['law firm','lawyer','lawyers','advocate','advocates','legal consultant','legal services','attorney']::text[], '{}'::text[], array['lawyer']::text[], '[{"key":"office","value":"lawyer"}]'::jsonb, 1.4),
  (null, 'auto_repair', 'Auto Repair', array['auto repair','car repair','garage','mechanic','auto workshop','car service','car garage','auto service']::text[], '{}'::text[], array['car_repair']::text[], '[{"key":"shop","value":"car_repair"}]'::jsonb, 1.1),
  (null, 'tailors', 'Tailors', array['tailor','tailors','tailoring','alterations','abaya tailor','bespoke tailoring','stitching']::text[], '{}'::text[], '{}'::text[], '[{"key":"craft","value":"tailor"},{"key":"shop","value":"tailor"}]'::jsonb, 0.85),
  (null, 'bakeries', 'Bakeries', array['bakery','bakeries','cake shop','patisserie','custom cakes','desserts','pastry shop']::text[], '{}'::text[], array['bakery']::text[], '[{"key":"shop","value":"bakery"},{"key":"shop","value":"pastry"}]'::jsonb, 1),
  (null, 'hotels', 'Hotels', array['hotel','hotels','hotel apartments','guest house','boutique hotel','resort','hostel']::text[], array['international chain']::text[], array['hotel','lodging']::text[], '[{"key":"tourism","value":"hotel"},{"key":"tourism","value":"guest_house"}]'::jsonb, 1.3),
  (null, 'travel_agencies', 'Travel Agencies', array['travel agency','travel agent','tour operator','tours','visa services','holiday packages','desert safari']::text[], '{}'::text[], array['travel_agency']::text[], '[{"key":"shop","value":"travel_agency"},{"key":"office","value":"travel_agent"}]'::jsonb, 1.15)
on conflict do nothing;

-- Default organisation (Ain AlTair). Additional organisations can be added later.
insert into public.organisations (name, slug, default_currency, default_country_code, timezone)
values ('Ain AlTair', 'ain-altair', 'AED', 'AE', 'Asia/Dubai')
on conflict (slug) do nothing;

-- Register providers + default settings for every organisation (idempotent).
create or replace function public.bootstrap_organisation(org_id uuid)
returns void language plpgsql security definer set search_path = public as $$
begin
  insert into public.providers (organisation_id, key, name, kind, priority, rate_limit_per_minute) values
    (org_id, 'google_places', 'Google Places API (New)', 'DISCOVERY', 10, 120),
    (org_id, 'apify_google_maps', 'Apify — Google Maps Scraper', 'DISCOVERY', 20, 10),
    (org_id, 'osm_overpass', 'OpenStreetMap (Overpass API)', 'DISCOVERY', 30, 6),
    (org_id, 'brave_search', 'Brave Search API', 'ENRICHMENT', 40, 50),
    (org_id, 'website_audit', 'Built-in Website Auditor', 'AUDIT', 50, 60),
    (org_id, 'pagespeed', 'Google PageSpeed Insights', 'AUDIT', 55, 60),
    (org_id, 'nominatim', 'OpenStreetMap Nominatim', 'GEOCODING', 60, 50),
    (org_id, 'anthropic', 'Claude (Anthropic API)', 'AI', 70, 50),
    (org_id, 'google_sheets', 'Google Sheets', 'INTEROP', 80, 60)
  on conflict (organisation_id, key) do update set name = excluded.name, kind = excluded.kind;
  insert into public.org_settings (organisation_id) values (org_id) on conflict do nothing;
end $$;
revoke all on function public.bootstrap_organisation(uuid) from public, anon, authenticated;

select public.bootstrap_organisation(id) from public.organisations;

create or replace function public.on_organisation_created()
returns trigger language plpgsql security definer set search_path = public as $$
begin
  perform public.bootstrap_organisation(new.id);
  return new;
end $$;
create trigger organisations_bootstrap after insert on public.organisations
  for each row execute function public.on_organisation_created();
